# Generated by Django 2.1.4 on 2019-01-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='author_headshots'),
        ),
    ]
