# Generated by Django 2.1.5 on 2019-01-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0002_auto_20190105_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
        migrations.AddField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='author_dp'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover_pic'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_dp'),
        ),
    ]
