# Generated by Django 2.1.5 on 2019-01-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0003_auto_20190127_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewedBy', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookReviews', to='BAP.Book')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
