# Generated by Django 2.1.5 on 2019-02-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0007_auto_20190131_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bookReview',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-genre']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
