# Generated by Django 2.1.5 on 2019-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0008_auto_20190201_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
