# Generated by Django 2.1.5 on 2019-02-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0009_publisher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='BookAuthors', to='BAP.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublisherBook', to='BAP.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublisherUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
