# Generated by Django 2.1.5 on 2019-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0010_auto_20190208_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='BookAuthors', to='BAP.Book'),
        ),
    ]
