# Generated by Django 2.1.5 on 2019-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0011_auto_20190209_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='BookAuthors', to='BAP.Author'),
        ),
    ]
