# Generated by Django 2.1.5 on 2019-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAP', '0013_remove_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='BookAuthors', to='BAP.Author'),
        ),
    ]
